#!/bin/bash

# Siyuan: This script processes monthly data in a setup purpose. After maintenance period we need another cron job to do this.
# Also make sure that the dates are all June 1st inside files 
base="2022/06/"
olddate=""

for i in {1..3}
do
    day=""

    if (($i <= 10))
    then
    day+="0"
    fi

    day+=$i
    date="$base$day"

    if [ ! -z "$olddate" ]
    then
        let yesterday=$i-1
        yesterday="time.June, $yesterday"
        today="time.June, $i"
        
        # Update the dates in files
        sed -i -e "s|$olddate|$date|g" ~/config/configs/canada-test/config.go
        sed -i -e "s|$olddate|$date|g" ~/data-processing/xmode-import/service/src/main.go
        sed -i -e "s|$yesterday|$today|g" ~/data-processing/visits-processing/service/src/main.go
    fi

    # Run data processing
    cd ~/data-processing/xmode-import/service/dev && sudo make run CONFIG=canada-test
    cd ~/data-processing/visits-processing/service/dev && sudo make run CONFIG=canada-test

    # Prepare for next day
    olddate=$date
done

# Stop instance
aws ec2 stop-instances --instance-ids i-0927dc84f6fdda8d3
